Repository Alfresco/alfresco-docker-base-java, pull requests merged in 2022-02, with the labels that each got.

#76 OPSEXP-1046 java base multistage build
  .github/dependabot.yml
  .github/workflows/main.yml
  .travis.yml
  Dockerfile
  README.md
  centos-7/Dockerfile
  debian-11/Dockerfile
  ubi-8/Dockerfile
  ubuntu-20.04/Dockerfile
Labels: PR: unreviewed

#80 OPSEXP-1236: fix and harden dependabot config
  .github/dependabot.yml
Labels: PR: reviewed-approved

#81 OPSEXP-1257 build alpine base image
  .github/workflows/main.yml
  Dockerfile
Labels: PR: partially-approved

#83 OPSEXP-1257 make sure alpine base is updated
  Dockerfile
Labels: PR: reviewed-approved
