Repository Alfresco/alfresco-docker-base-java, pull requests merged in 2022-03, with the labels that each got.

#87 OPSEXP-1295: fix python-lxml vulnerability
  .github/workflows/main.yml
  Dockerfile
Labels: PR: partially-approved

#89 OPSEXP-1320 Add rockylinux flavour
  .github/workflows/main.yml
  Dockerfile
Labels: PR: unreviewed

#88 OPSEXP-1294 README rewrite with emphasis on how to use it
  README.md
Labels: PR: reviewed-approved
